version: "3.9"

services:
  database:
    container_name: postgres_testing
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  php-fpm:
    container_name: php-fpm_testing
    build:
      context: ./php-fpm
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../:/var/www
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx_testing
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/environment/local/sites/:/etc/nginx/sites-available
      - ./nginx/environment/local/conf.d/:/etc/nginx/conf.d
    # - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
